### ISSUE TITLE
New Module Checklist

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-chatbots#2]
### Issue description

- [x] Use [Project template](https://github.com/micronaut-projects/micronaut-project-template) to create a new repository.

- [x]  Prefix the repository with micronaut-.
- [x]  Add the [project to file sync](https://github.com/micronaut-projects/micronaut-project-template/blob/master/.github/workflows/files-sync.yml#L14) without the micronaut- prefix.
- [x]  Add the module to [management](https://github.com/micronaut-projects/management/blob/master/repos.auto.tfvars)[](https://github.com/micronaut-projects/micronaut-core/wiki/_new?wiki%5Bname%5D=_Footer) repository.
